### ISSUE TITLE
Fix webcal.fi

### ISSUE THREAD

**Issue by metbril** [metbril/home-assistant-config#56]
The Webcal.fi website has moved to webcal.guru and now requires an active subscription. The free account only provides ICS and no longer supports JSON. So I need to update the Holidays and Flagdays sensors. Have disabled them for now.

**Comment by metbril** [comment]
7a69344a2cc7238805c04349538f54fa989935a7

**Comment by metbril** [comment]
That was easy. I've managed to get 2 Web Guru calendars into Home Assistant. I'm experimenting a little and once I have things working as they should, I'll push it to the repo.

1. Install the [ICS Calendar integration][ics] through [HACS][hacs] and restart Home Assistant
2. Create account with [Webcal Guru][guru]
3. Go to your account page and copy the calendar url to your clipboard. It looks something like https://www.webcal.guru/nl-NL/kalender_downloaden?subscription_id=xxx
4. Paste that url into your YAML configuration

```yaml
calendar:
  - platform: ics_calendar
    calendars:
      - name: "Feestdagen"  # public holidays
        url: "https://www.webcal.guru/nl-NL/kalender_downloaden?subscription_id=xxx"
        days: 2  # look ahead 1 day
        include_all_day: true
        download_interval: 60 ## minutes
      - name: "Vlagdagen"  # flag days
        url: "https://www.webcal.guru/nl-NL/kalender_downloaden?subscription_id=yyy"
        days: 2  # look ahead 1 day
        include_all_day: true
        download_interval: 60 ## minutes
```

[ics]: https://github.com/franc6/ics_calendar
[hacs]: https://hacs.xyz
[guru]: https://www.webcal.guru/
