### ISSUE TITLE
Tweet new follower

### ISSUE THREAD

**Issue by metbril** [metbril/home-assistant-config#59]
https://github.com/CCOSTAN/Home-AssistantConfig/blob/2d99c30e943298cd0201a6ba0d3c5938c392b8ce/config/packages/twitter.yaml#L177

```
  - alias: 'Twitter: New follower!'
    id: 7b093026-2635-4d43-bfa1-74130f3040f5
    initial_state: false
    mode: single

    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: new_follower

    condition: []

    action:
      - service: media_player.play_media
        data:
          entity_id:
            - media_player.woonkamer
            - media_player.kantoor
          media_content_id: "https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/twitter-chirp.mp3"
          media_content_type: audio/mp4
```
